os: linux
language: python
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

jobs:
  fast_finish: true

sudo: true
before_install:
  - curl -L https://github.com/jgm/pandoc/releases/download/2.9.1.1/pandoc-2.9.1.1-1-amd64.deb > pandoc.deb
  - sudo dpkg -i pandoc.deb

install:
  - pip install pytest==4.6.* -r requirements.txt

script:
  - python -m pytest
