os: linux
language: python
cache: pip

python:
  - "2.7"
  - "3.4"
  - "3.5"
  - "3.6"
  - "3.7"
  - "3.8"

env:
  - pandocVersion=latest

jobs:
  fast_finish: true

before_install:
  - |
    url="https://github.com/jgm/pandoc/releases/latest"
    path=$(curl -L $url | grep -o '/jgm/pandoc/releases/download/.*-amd64\.deb')
    downloadUrl="https://github.com$path"
    file=${path##*/}

install:
  - wget $downloadUrl &&
    sudo dpkg -i $file
  - pip install -e .

script:
  - pytest
